Models/ErrorViewModel.cs
namespace MyTestProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyTestProject.ClassesEntity;
using Microsoft.EntityFrameworkCore; // For EF Core extensions
using Microsoft.Extensions.Logging; // For ILogger

using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyTestProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly MyIndexInformation _context; // Use your DbContext type

        public HomeController(ILogger<HomeController> logger, MyIndexInformation context) // Inject DbContext
        {
            _logger = logger;
            _context = context; // Assign injected DbContext to the field
        }

        public async Task<IActionResult> Index()
        {
            _logger.LogError("Index action is started!");
            List<IndexPagesInformation> indexPagesList = await _context.IndexInfo.ToListAsync();
            return View(indexPagesList[0]);
        }

        public IActionResult OurShop()
        {
            return View(); 
        }
    }
}

Controllers/MembersController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyTestProject.Controllers
{
    public class MembersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SignIn()
        {
            return View();
        }
    }
}

Views/Home/OurShop.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Lugx Gaming - Shop Page</title>

    <!-- Bootstrap core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="/assets/css/fontawesome.css">
    <link rel="stylesheet" href="/assets/css/templatemo-lugx-gaming.css">
    <link rel="stylesheet" href="/assets/css/owl.css">
    <link rel="stylesheet" href="/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
    <!--

    TemplateMo 589 lugx gaming

    https://templatemo.com/tm-589-lugx-gaming

    -->
</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">
                            <img src="/assets/images/logo.png" alt="" style="width: 158px;">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a href="index.html">Home</a></li>
                            <li><a href="shop.html" class="active">Our Shop</a></li>
                            <li><a href="product-details.html">Product Details</a></li>
                            <li><a href="contact.html">Contact Us</a></li>
                            <li><a href="#">Sign In</a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <div class="page-heading header-text">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h3>Our Shop</h3>
                    <span class="breadcrumb"><a href="#">Home</a> > Our Shop</span>
                </div>
            </div>
        </div>
    </div>

    <div class="section trending">
        <div class="container">
            <ul class="trending-filter">
                <li>
                    <a class="is_active" href="#!" data-filter="*">Show All</a>
                </li>
                <li>
                    <a href="#!" data-filter=".adv">Adventure</a>
                </li>
                <li>
                    <a href="#!" data-filter=".str">Strategy</a>
                </li>
                <li>
                    <a href="#!" data-filter=".rac">Racing</a>
                </li>
            </ul>
            <div class="row trending-box">
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 adv">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-01.jpg" alt=""></a>
                            <span class="price"><em>$36</em>$24</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 str">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-02.jpg" alt=""></a>
                            <span class="price"><em>$32</em>$22</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 adv rac">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-03.jpg" alt=""></a>
                            <span class="price"><em>$45</em>$30</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 str">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-04.jpg" alt=""></a>
                            <span class="price"><em>$32</em>$22</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 rac str">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-03.jpg" alt=""></a>
                            <span class="price"><em>$38</em>$26</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 rac adv">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-01.jpg" alt=""></a>
                            <span class="price"><em>$30</em>$20</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 rac str">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-04.jpg" alt=""></a>
                            <span class="price"><em>$32</em>$22</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 rac adv">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-02.jpg" alt=""></a>
                            <span class="price"><em>$32</em>$22</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 adv rac">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-03.jpg" alt=""></a>
                            <span class="price"><em>$28</em>$20</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 str">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-04.jpg" alt=""></a>
                            <span class="price"><em>$26</em>$18</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 adv">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-01.jpg" alt=""></a>
                            <span class="price"><em>$32</em>$24</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 str">
                    <div class="item">
                        <div class="thumb">
                            <a href="product-details.html"><img src="/assets/images/trending-02.jpg" alt=""></a>
                            <span class="price"><em>$45</em>$30</span>
                        </div>
                        <div class="down-content">
                            <span class="category">Action</span>
                            <h4>Assasin Creed</h4>
                            <a href="product-details.html"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="pagination">
                        <li><a href="#"> &lt; </a></li>
                        <li><a href="#">1</a></li>
                        <li><a class="is_active" href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#"> &gt; </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="col-lg-12">
                <p>Copyright © 2048 LUGX Gaming Company. All rights reserved. &nbsp;&nbsp; <a rel="nofollow" href="https://templatemo.com" target="_blank">Design: TemplateMo</a></p>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/js/isotope.min.js"></script>
    <script src="/assets/js/owl-carousel.js"></script>
    <script src="/assets/js/counter.js"></script>
    <script src="/assets/js/custom.js"></script>

</body>
</html>

Views/Members/Index.cshtml
<html>
	<head>
        <style>@@use postcss-preset-env {
  stage: 0;
}

/* config.css */

:root {
  --baseColor: #606468;
}

/* helpers/align.css */

.align {
  display: grid;
  place-items: center;
}

.grid {
  inline-size: 90%;
  margin-inline: auto;
  max-inline-size: 20rem;
}

/* helpers/hidden.css */

.hidden {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}

/* helpers/icon.css */

:root {
  --iconFill: var(--baseColor);
}

.icons {
  display: none;
}

.icon {
  block-size: 1em;
  display: inline-block;
  fill: var(--iconFill);
  inline-size: 1em;
  vertical-align: middle;
}

/* layout/base.css */

:root {
  --htmlFontSize: 100%;

  --bodyBackgroundColor: #2c3338;
  --bodyColor: var(--baseColor);
  --bodyFontFamily: "Open Sans";
  --bodyFontFamilyFallback: sans-serif;
  --bodyFontSize: 0.875rem;
  --bodyFontWeight: 400;
  --bodyLineHeight: 1.5;
}

* {
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
  font-size: var(--htmlFontSize);
}

body {
  background-color: var(--bodyBackgroundColor);
  color: var(--bodyColor);
  font-family: var(--bodyFontFamily), var(--bodyFontFamilyFallback);
  font-size: var(--bodyFontSize);
  font-weight: var(--bodyFontWeight);
  line-height: var(--bodyLineHeight);
  margin: 0;
  min-block-size: 100vh;
}

/* modules/anchor.css */

:root {
  --anchorColor: #eee;
}

a {
  color: var(--anchorColor);
  outline: 0;
  text-decoration: none;
}

a:focus,
a:hover {
  text-decoration: underline;
}

/* modules/form.css */

:root {
  --formGap: 0.875rem;
}

input {
  background-image: none;
  border: 0;
  color: inherit;
  font: inherit;
  margin: 0;
  outline: 0;
  padding: 0;
  transition: background-color 0.3s;
}

input[type="submit"] {
  cursor: pointer;
}

.form {
  display: grid;
  gap: var(--formGap);
}

.form input[type="password"],
.form input[type="text"],
.form input[type="submit"] {
  inline-size: 100%;
}

.form__field {
  display: flex;
}

.form__input {
  flex: 1;
}

/* modules/login.css */

:root {
  --loginBorderRadus: 0.25rem;
  --loginColor: #eee;

  --loginInputBackgroundColor: #3b4148;
  --loginInputHoverBackgroundColor: #434a52;

  --loginLabelBackgroundColor: #363b41;

  --loginSubmitBackgroundColor: #ea4c88;
  --loginSubmitColor: #eee;
  --loginSubmitHoverBackgroundColor: #d44179;
}

.login {
  color: var(--loginColor);
}

.login label,
.login input[type="text"],
.login input[type="password"],
.login input[type="submit"] {
  border-radius: var(--loginBorderRadus);
  padding: 1rem;
}

.login label {
  background-color: var(--loginLabelBackgroundColor);
  border-bottom-right-radius: 0;
  border-top-right-radius: 0;
  padding-inline: 1.25rem;
}

.login input[type="password"],
.login input[type="text"] {
  background-color: var(--loginInputBackgroundColor);
  border-bottom-left-radius: 0;
  border-top-left-radius: 0;
}

.login input[type="password"]:focus,
.login input[type="password"]:hover,
.login input[type="text"]:focus,
.login input[type="text"]:hover {
  background-color: var(--loginInputHoverBackgroundColor);
}

.login input[type="submit"] {
  background-color: var(--loginSubmitBackgroundColor);
  color: var(--loginSubmitColor);
  font-weight: 700;
  text-transform: uppercase;
}

.login input[type="submit"]:focus,
.login input[type="submit"]:hover {
  background-color: var(--loginSubmitHoverBackgroundColor);
}

/* modules/text.css */

p {
  margin-block: 1.5rem;
}

.text--center {
  text-align: center;
}
</style>
	</head>
    <body>
    <body class="align">

        <div class="grid">

            <form action="https://httpbin.org/post" method="POST" class="form login">

                <div class="form__field">
                    <label for="login__username">
                        <svg class="icon">
                            <use xlink:href="#icon-user"></use>
                        </svg><span class="hidden">Username</span>
                    </label>
                    <input autocomplete="username" id="login__username" type="text" name="username" class="form__input" placeholder="Username" required>
                </div>

                <div class="form__field">
                    <label for="login__password">
                        <svg class="icon">
                            <use xlink:href="#icon-lock"></use>
                        </svg><span class="hidden">Password</span>
                    </label>
                    <input id="login__password" type="password" name="password" class="form__input" placeholder="Password" required>
                </div>

                <div class="form__field">
                    <input type="submit" value="Sign In">
                </div>

            </form>

            <p class="text--center">
                Not a member? <a asp-action="SignIn" asp-controller="Members">Sign up now</a>
                <svg class="icon">
                    <use xlink:href="#icon-arrow-right"></use>
                </svg>
            </p>

        </div>

        <svg xmlns="http://www.w3.org/2000/svg" class="icons">
            <symbol id="icon-arrow-right" viewBox="0 0 1792 1792">
                <path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z" />
            </symbol>
            <symbol id="icon-lock" viewBox="0 0 1792 1792">
                <path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z" />
            </symbol>
            <symbol id="icon-user" viewBox="0 0 1792 1792">
                <path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z" />
            </symbol>
        </svg>

    </body>
    </body>
</<html>

Views/Members/SignIn.cshtml
<html>
<head>
    <style>
        @@use postcss-preset-env {
            stage: 0;
        }

        /* config.css */

        :root {
            --baseColor: #606468;
        }

        /* helpers/align.css */

        .align {
            display: grid;
            place-items: center;
        }

        .grid {
            inline-size: 90%;
            margin-inline: auto;
            max-inline-size: 20rem;
        }

        /* helpers/hidden.css */

        .hidden {
            border: 0;
            clip: rect(0 0 0 0);
            height: 1px;
            margin: -1px;
            overflow: hidden;
            padding: 0;
            position: absolute;
            width: 1px;
        }

        /* helpers/icon.css */

        :root {
            --iconFill: var(--baseColor);
        }

        .icons {
            display: none;
        }

        .icon {
            block-size: 1em;
            display: inline-block;
            fill: var(--iconFill);
            inline-size: 1em;
            vertical-align: middle;
        }

        /* layout/base.css */

        :root {
            --htmlFontSize: 100%;
            --bodyBackgroundColor: #2c3338;
            --bodyColor: var(--baseColor);
            --bodyFontFamily: "Open Sans";
            --bodyFontFamilyFallback: sans-serif;
            --bodyFontSize: 0.875rem;
            --bodyFontWeight: 400;
            --bodyLineHeight: 1.5;
        }

        * {
            box-sizing: inherit;
        }

        html {
            box-sizing: border-box;
            font-size: var(--htmlFontSize);
        }

        body {
            background-color: var(--bodyBackgroundColor);
            color: var(--bodyColor);
            font-family: var(--bodyFontFamily), var(--bodyFontFamilyFallback);
            font-size: var(--bodyFontSize);
            font-weight: var(--bodyFontWeight);
            line-height: var(--bodyLineHeight);
            margin: 0;
            min-block-size: 100vh;
        }

        /* modules/anchor.css */

        :root {
            --anchorColor: #eee;
        }

        a {
            color: var(--anchorColor);
            outline: 0;
            text-decoration: none;
        }

            a:focus,
            a:hover {
                text-decoration: underline;
            }

        /* modules/form.css */

        :root {
            --formGap: 0.875rem;
        }

        input {
            background-image: none;
            border: 0;
            color: inherit;
            font: inherit;
            margin: 0;
            outline: 0;
            padding: 0;
            transition: background-color 0.3s;
        }

            input[type="submit"] {
                cursor: pointer;
            }

        .form {
            display: grid;
            gap: var(--formGap);
        }

            .form input[type="password"],
            .form input[type="text"],
            .form input[type="submit"] {
                inline-size: 100%;
            }

        .form__field {
            display: flex;
        }

        .form__input {
            flex: 1;
        }

        /* modules/login.css */

        :root {
            --loginBorderRadus: 0.25rem;
            --loginColor: #eee;
            --loginInputBackgroundColor: #3b4148;
            --loginInputHoverBackgroundColor: #434a52;
            --loginLabelBackgroundColor: #363b41;
            --loginSubmitBackgroundColor: #ea4c88;
            --loginSubmitColor: #eee;
            --loginSubmitHoverBackgroundColor: #d44179;
        }

        .login {
            color: var(--loginColor);
        }

            .login label,
            .login input[type="text"],
            .login input[type="password"],
            .login input[type="submit"] {
                border-radius: var(--loginBorderRadus);
                padding: 1rem;
            }

            .login label {
                background-color: var(--loginLabelBackgroundColor);
                border-bottom-right-radius: 0;
                border-top-right-radius: 0;
                padding-inline: 1.25rem;
            }

            .login input[type="password"],
            .login input[type="text"] {
                background-color: var(--loginInputBackgroundColor);
                border-bottom-left-radius: 0;
                border-top-left-radius: 0;
            }

                .login input[type="password"]:focus,
                .login input[type="password"]:hover,
                .login input[type="text"]:focus,
                .login input[type="text"]:hover {
                    background-color: var(--loginInputHoverBackgroundColor);
                }

            .login input[type="submit"] {
                background-color: var(--loginSubmitBackgroundColor);
                color: var(--loginSubmitColor);
                font-weight: 700;
                text-transform: uppercase;
            }

                .login input[type="submit"]:focus,
                .login input[type="submit"]:hover {
                    background-color: var(--loginSubmitHoverBackgroundColor);
                }

        /* modules/text.css */

        p {
            margin-block: 1.5rem;
        }

        .text--center {
            text-align: center;
        }
    </style>
</head>
<body>
    <body class="align">

        <div class="grid">

            <form action="https://httpbin.org/post" method="POST" class="form login">

                <div class="form__field">
                    <label for="login__username">
                        <svg class="icon">
                            <use xlink:href="#icon-user"></use>
                        </svg><span class="hidden">Username</span>
                    </label>
                    <input autocomplete="username" id="login__username" type="text" name="username" class="form__input" placeholder="Username" required>
                </div>

                <div class="form__field">
                    <label for="login__password">
                        <svg class="icon">
                            <use xlink:href="#icon-lock"></use>
                        </svg><span class="hidden">Password</span>
                    </label>
                    <input id="login__password" type="password" name="password" class="form__input" placeholder="Password" required>
                </div>

                <div class="form__field">
                    <input type="submit" value="Sign In">
                </div>

            </form>

            <p class="text--center">
                are you a member? <a href="#">Log in  now</a>
                <svg class="icon">
                    <use xlink:href="#icon-arrow-right"></use>
                </svg>
            </p>

        </div>

        <svg xmlns="http://www.w3.org/2000/svg" class="icons">
            <symbol id="icon-arrow-right" viewBox="0 0 1792 1792">
                <path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z" />
            </symbol>
            <symbol id="icon-lock" viewBox="0 0 1792 1792">
                <path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z" />
            </symbol>
            <symbol id="icon-user" viewBox="0 0 1792 1792">
                <path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z" />
            </symbol>
        </svg>

    </body>
</body>
</
<html>

Views/Shared/_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

    @RenderBody()